module pl {
    module kumon {
        module transfertester {
            module tester {
                module corba {

                    interface CorbaConnector {
                        string get();
                    };
                };
            };
        };
    };
};