/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_kumon_transfertester_tester_jni_JniExcecutor */

#ifndef _Included_pl_kumon_transfertester_tester_jni_JniExcecutor
#define _Included_pl_kumon_transfertester_tester_jni_JniExcecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_kumon_transfertester_tester_jni_JniExcecutor
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pl_kumon_transfertester_tester_jni_JniExcecutor_stringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
