module pl {
    module kumon {
        module transfertester {
            module tester {
                module corba {

                    interface CorbaConnector {
                        string get(in long responseSize, in string request);
                    };
                };
            };
        };
    };
};
